FROM python:3.11-slim AS builder

WORKDIR /app

# Установка виртуального окружения и сборка пакетов
RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Финальный минимальный образ
FROM python:3.11-slim

WORKDIR /app

# Копируем только готовое виртуальное окружение из builder
COPY --from=builder /opt/venv /opt/venv
COPY main.py .

# Активируем виртуальное окружение в финальном контейнере
ENV PATH="/opt/venv/bin:$PATH"
EXPOSE 80

# Запуск uvicorn на 80 порту
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
